// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTRlB56QjEykvIcjBMuUrgiU3AdeA31-U',
    appId: '1:676956156660:web:0930a9ab3ae5c387cee4a1',
    messagingSenderId: '676956156660',
    projectId: 'entscheider-app',
    authDomain: 'entscheider-app.firebaseapp.com',
    storageBucket: 'entscheider-app.appspot.com',
    measurementId: 'G-0B4SR8Z2DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaKf3n2JDjtbuEsq8Ipo_kgOCQ6casHxs',
    appId: '1:676956156660:android:fe41c00d1ce3ff9ecee4a1',
    messagingSenderId: '676956156660',
    projectId: 'entscheider-app',
    storageBucket: 'entscheider-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnBvp3OJxawGvPvyX-3F63v0myS-_TnX4',
    appId: '1:676956156660:ios:9952258a4c126e4ecee4a1',
    messagingSenderId: '676956156660',
    projectId: 'entscheider-app',
    storageBucket: 'entscheider-app.appspot.com',
    iosBundleId: 'com.example.entscheiderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnBvp3OJxawGvPvyX-3F63v0myS-_TnX4',
    appId: '1:676956156660:ios:d38e12802bb7a479cee4a1',
    messagingSenderId: '676956156660',
    projectId: 'entscheider-app',
    storageBucket: 'entscheider-app.appspot.com',
    iosBundleId: 'com.example.entscheiderApp.RunnerTests',
  );
}
